### ISSUE TITLE
duplicate notification of star event

### ISSUE THREAD

**Issue by kenautomus** [cslant/telegram-git-notifier#42]
Hello,
When I changed the star event's condition to true, I saw that it started sending notifications twice.

```json
"star": {
  "created": true,
  "deleted": true
},
```

I have checked and fixed [the pull request](https://github.com/cslant/laravel-telegram-git-notifier/pull/62). Please help me check.
Thanks!

**Comment by tanhongit** [comment]
thanks!
please wait for me to check.

**Comment by kenautomus** [comment]
This PR is also related #41
